"""add transaction module

Revision ID: b6234928c2bb
Revises: 8060a26a2d52
Create Date: 2026-05-19 23:47:05.534575

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b6234928c2bb"
down_revision: Union[str, None] = "8060a26a2d52"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
import app.utilities.orm
from app.models.enums.transaction import TransactionType


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("wallet_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(), nullable=False),
        sa.Column(
            "transaction_type",
            app.utilities.orm.EnumValue(TransactionType, native_enum=False),
            nullable=False,
        ),
        sa.Column("reference_id", sa.String(), nullable=True),
        sa.Column(
            "created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "modified_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "wallets",
        "balance",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "wallets",
        "balance",
        existing_type=sa.Numeric(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.drop_table("transactions")
    # ### end Alembic commands ###
